### ISSUE TITLE
Review Request

### ISSUE THREAD

**Issue by lpodev** [LPOdev/GPR1-SocialNetwork#4]
@NicolasGlassey 
https://github.com/lpodev/GPR1-SocialNetwork/commit/0bfa1a2c82d2eb797aa5b83db455d6150d8c2bfd

Je n'ai pas réussi à passer le test "test_constructor_InstantiationWithDuplicatedSubscribers_ThrowsException", j'ai compris ce qu'il lui faut, je n'ai juste pas eu assez de temps pour trouver la bonne façon de faire.

Au moment du test, on va d'abords créer des Followers, ensuite on va "cloner" le premier et l'idée pour réussir ce test serait de parcourir la liste des Followers qui existent déjà et pouvoir ainsi comparer avec le "clone". Si le "clone" existe déjà, on lance l'exception "SubscriberAlreadyExistsException".

Ce serait quelque chose comme:
```
foreach($followersList as $follower)
{
   if($follower = $observer)
   {
     throw new SubscriberAlreadyExistsException();
   }
}
```

**Comment by NicolasGlassey** [comment]
@lpodev 

Bonjour Luis,

J'ai pris en compte cette issue pour l'évaluation.

Bonne suite de week-end !
